### ISSUE TITLE
ImportError: pyplot() command requires matplotlib

### ISSUE THREAD

**Issue by ahmedshingaly** [tejasmorkar/sketch-to-color#3]
thank you for the deep and simplified explanations of ML deployment
I am facing an issue running streamlit file as described in your article. 

![error1](https://user-images.githubusercontent.com/17035943/100819804-43102a80-3490-11eb-89c1-c791b315002a.PNG)

thank you in advance

**Comment by tejasmorkar** [comment]
Hi @ahmedshingaly , I think that you have not installed matplotlib library in your environment. Try running the app after installing it. 

`pip install matplotlib`

**Comment by ahmedshingaly** [comment]
thank you for the quick reply, matplotlib already installed. I will read your article more deeply and try to solve the problem, will let you know if I couldn't solve it. 

best 
Ahmed

**Comment by tejasmorkar** [comment]
> will let you know if I couldn't solve it

Okay, sure.
